### ISSUE TITLE
Integration no longer loads with 2023.5 HAOS update.

### ISSUE THREAD

**Issue by balucanb** [prestomation/resmed_myair_sensors#34]
After updating HAOS to 2023.5 the integration is not loading.
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/resmed_myair/__init__.py:23
Integration: ResMed myAir CPAP Sensors (documentation, issues)
First occurred: 07:12:46 (1 occurrences)
Last logged: 07:12:46

Error setting up entry ResMed-AirSense 10 Respond for resmed_myair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/resmed_myair/__init__.py", line 23, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

VERSION- 0.1.10

Not sure what else you need if you require more info please explain to me. I have included everything I understood.

```

**Comment by Bosswaffle** [comment]
This is another duplicate of #30 "Change to async_forward_entry_setups"

**Comment by prestomation** [comment]
fixed with #29

**Comment by balucanb** [comment]
Thanks!
